# Everything related to vector should be in this namespace
apiVersion: v1
kind: Namespace
metadata:
   name: telemetry
   
---
# ConfigMap which contains vector.toml configuration for pods.
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: telemetry
data:
  vector-agent-config: |
    # VECTOR.TOML
    # Configuration for vector-agent

    # Set global options
    data_dir = "/var/tmp/vector"

    # Ingest logs from Kubernetes
    [sources.kubernetes_logs]
      type = "kubernetes"

    ######
    # NOTE: Here, vector can be configured  
    ######

  # This line is not in VECTOR.TOML       

---
# Vector agent runned on each Node where it collects logs from pods.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector-agent
  namespace: telemetry
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      name: vector-agent
  template:
    metadata:
      labels:
        name: vector-agent
    spec:
      volumes:
      # Directory with logs
      - name: var-log
        hostPath:
          path: /var/log/
      # Docker and containerd log files in Kubernetes are symlinks to this folder.
      - name: var-lib
        hostPath:
          path: /var/lib/
      # Vector will store it's data here.
      - name: data-dir
        emptyDir: {}
      # Mount vector configuration from config map as a file vector.toml
      - name: config-dir
        configMap:
         name: vector-config
         items:
           - key: vector-agent-config
             path: vector.toml
      containers:
      - name: vector
        # TODO: update to a proper version which contains kubernetes source.
        image: timberio/vector:0.4.0-alpine
        imagePullPolicy: Always
        args: ["-c","/etc/vector/vector.toml"]
        volumeMounts:
        - name: var-log
          mountPath: /var/log/
          readOnly: true        
        - name: var-lib
          mountPath: /var/lib
          readOnly: true 
        - name: data-dir
          mountPath: /var/tmp/vector
        - name: config-dir
          mountPath: /etc/vector
          readOnly: true 