[sinks.kafka]
buffer = true
common = true
delivery_guarantee = "at_least_once"
egress_method = "streaming"
encodings = ["json", "text"]
function_category = "transmit"
healthcheck = true
input_types = ["log"]
service_provider = "Confluent"
write_to_description = "[Apache Kafka][urls.kafka] via the [Kafka protocol][urls.kafka_protocol]"
tls_options = ["+enabled", "-verify"]

[sinks.kafka.options.bootstrap_servers]
type = "[string]"
common = true
examples = [["10.14.22.123:9092", "10.14.23.332:9092"]]
null = false
description = """\
A list of host and port pairs that the Kafka client should contact to bootstrap \
its cluster metadata.\
"""

[sinks.kafka.options.key_field]
type = "string"
common = true
examples = ["user_id"]
null = false
description = """\
The log field name to use for the topic key. If unspecified, the key will be \
randomly generated. If the field does not exist on the log, a blank value \
will be used.\
"""

[sinks.kafka.options.topic]
type = "string"
common = true
examples = ["topic-1234"]
null = false
description = "The Kafka topic name to write events to."

[sinks.kafka.options.sasl]
type = "table"
null = true
description = "Options for SASL/SCRAM authentication support"

[sinks.kafka.options.sasl.options.enabled]
type = "bool"
null = true
default = false
description = "Enable SASL/SCRAM authentication to the remote."

[sinks.kafka.options.sasl.options.username]
type = "string"
common = true
examples = ["username"]
null = false
description = "The Kafka SASL/SCRAM authentication username."

[sinks.kafka.options.sasl.options.password]
type = "string"
common = true
examples = ["password"]
null = false
description = "The Kafka SASL/SCRAM authentication password."

[sinks.kafka.options.sasl.options.mechanism]
type = "string"
common = true
examples = ["SCRAM-SHA-256", "SCRAM-SHA-512"]
null = false
description = "The Kafka SASL/SCRAM mechanisms."
