# Everything related to vector should be in this namespace
apiVersion: v1
kind: Namespace
metadata:
   name: logging
---
# ConfigMap which contains vector.toml configuration for pods.
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: logging
data:
  vector-agent-config: |
    # VECTOR.TOML
    # Configuration for vector-agent

    # Set global options
    data_dir = "/var/lib/vector/"

    # Ingest logs from Kubernetes
    [sources.kubernetes_logs]
      type = "kubernetes"

  # This line is not in VECTOR.TOML       

---
# Vector agent runned on each Node where it collects logs from pods.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector-agent
  namespace: logging
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      name: vector-agent
  template:
    metadata:
      labels:
        name: vector-agent
    spec:
      volumes:
      # Directory with logs
      - name: var-log
        hostPath:
          path: /var/log/
      # Docker log files in Kubernetes are symlinks to this folder.
      # Vector can persist local data in here. Having that, updated
      # Vector could continue where the last one stopped, if all the
      # used sources have that capability.
      - name: var-lib
        hostPath:
          path: /var/lib/
      # Mount vector configuration from config map as a file vector.toml
      - name: config-dir
        configMap:
         name: vector-config
         items:
           - key: vector-agent-config
             path: vector.toml
      containers:
      - name: vector
        # TODO: replace this with kubernetes version
        # TODO: can be done by merging first implementation and then tests
        image: timberio/vector:0.4.0
        imagePullPolicy: Always
        args: ["-c","/etc/vector/vector.toml"]
        volumeMounts:
        - name: var-log
          mountPath: /var/log/
          readOnly: true        
        - name: var-lib
          mountPath: /var/lib
        - name: config-dir
          mountPath: /etc/vector
          readOnly: true 
      # /var/lib/vector/ needs to be created
      initContainers:
      - name: init-vector-dir
        image: busybox:1.28
        command: ["mkdir","-p", "/var/lib/vector/"]
        volumeMounts:  
        - name: var-lib
          mountPath: /var/lib